name: 🐛 Report Bug (Easy)
description: Report any problem you find — quick and simple!
title: "[BUG] Brief description of the issue"
labels: ["bug"]
body:
  - type: textarea
    id: info
    attributes:
      label: What happened?
      description: Describe the issue in your own words. You can include steps, screenshots, context — anything that helps understand the bug.
      placeholder: |
        Example:
        - "When I do X, I expect Y, but Z happens."
        - "I got an error when trying to log in."
        - "Attaching a screenshot."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Where did it happen?
      description: Select the operating system and browser if you know it.
      options:
        - "I don’t know / Prefer not to say"
        - "Windows"
        - "Mac"
        - "Linux"
        - "iOS"
        - "Android"
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Anything else you’d like to add?
      description: If there’s anything else that helps understand the issue, write it here. (Optional)
      placeholder: |
        Example:
        - "This started happening today."
        - "It happens only sometimes."
        - "It blocks me from using the app."
    validations:
      required: false
