name: 🐛 Report a Bug
description: Something isn't working as it should
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Briefly describe what's not working
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What's happening instead?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      placeholder: If it's visual, share a screenshot or video
    validations:
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Mac
        - Linux
        - iOS
        - Android
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop
        - Tablet
        - Mobile
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: |
        - When did this start happening?
        - Does it happen every time or just sometimes?
        - Is this blocking your work?
    validations:
      required: false
