name: 💡 Suggest a Feature
description: Share an idea or improvement you'd love to see!
title: "[FEATURE] Briefly describe your idea"
labels: ["✨ enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What's your idea?
      description: Tell us what you’d like to see or improve. Feel free to be brief or detailed — whatever feels right.
      placeholder: |
        Example:
        - "It’d be awesome if we could export data to CSV."
        - "Add dark mode to make it easier on the eyes at night."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: Help us understand the value — what problem does it solve or what makes it cool?
      placeholder: |
        Example:
        - "It would save time when sharing reports."
        - "It makes the app more comfortable to use."
    validations:
      required: false
  - type: textarea
    id: extras
    attributes:
      label: Anything else?
      description: Add screenshots, examples, or related ideas (optional).
      placeholder: |
        Example:
        - "Similar to how Notion handles templates."
        - "Would pair nicely with the new dashboard."
    validations:
      required: false
