name: 💬 Ask a Question
description: Got a doubt or need clarification? Ask here!
title: "[QUESTION] Briefly describe your question"
labels: ["discussion"]
body:
  - type: textarea
    id: question
    attributes:
      label: What’s your question?
      description: Explain what you’d like to understand or clarify — in your own words.
      placeholder: |
        Example:
        - "How can I reset my password?"
        - "What’s the difference between X and Y?"
        - "Why does the app log me out after some time?"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Any context?
      description: (Optional) Tell us what you were trying to do or where you got stuck.
      placeholder: |
        Example:
        - "I was testing on Android."
        - "This happened right after updating."
        - "I’m using version 1.2.3."
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Add screenshots, what you’ve already tried, or anything that might help (optional).
      placeholder: |
        Example:
        - "I already checked the docs."
        - "It only happens sometimes."
    validations:
      required: false
